### ISSUE TITLE
Run a single test case?

### ISSUE THREAD

**Issue by smoelius** [assert-rs/snapbox#359]
With `trycmd`, is there a way to run just one [test case](https://docs.rs/trycmd/latest/trycmd/struct.TestCases.html)?

Something like:
```
TESTCASE="problematic_test_case_that_keeps_failing" cargo test ...
```
I've searched the issues and done a cursory scan of the code, but couldn't find the answer. Sorry if I overlooked something.

**Comment by epage** [comment]
This is covered in the [workflow documentation](https://docs.rs/trycmd/latest/trycmd/#workflow).  Its not too obvious but we were mirroring `trybuild` exactly:

```console
$ cargo test --test cli_tests -- cli_tests trycmd=name1 trycmd=name2...
```
- Select the test binary
- Select the test in that binary
- (Ab)use the test selection mechanism to name the test case

"Select the test in that binary" is important because if you only have `trycmd=`s then the test harness will find that no tests are matched and run nothing.

**Comment by smoelius** [comment]
Perfect! Thank you very much!
